/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AgentFlow: typeof import('./src/components/chat/AgentFlow.vue')['default']
    AgentTimeline: typeof import('./src/components/chat/AgentTimeline.vue')['default']
    AppLayout: typeof import('./src/components/layout/AppLayout.vue')['default']
    ChartContainer: typeof import('./src/components/chat/ChartContainer.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatWindow: typeof import('./src/components/chat/ChatWindow.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    GlassCard: typeof import('./src/components/common/GlassCard.vue')['default']
    HelpFloating: typeof import('./src/components/chat/HelpFloating.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/LoadingSpinner.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    NeonButton: typeof import('./src/components/common/NeonButton.vue')['default']
    NewSessionDialog: typeof import('./src/components/chat/NewSessionDialog.vue')['default']
    ParticleBg: typeof import('./src/components/common/ParticleBg.vue')['default']
    QuestionNav: typeof import('./src/components/chat/QuestionNav.vue')['default']
    RightPanel: typeof import('./src/components/chat/RightPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SessionList: typeof import('./src/components/chat/SessionList.vue')['default']
    SideMenu: typeof import('./src/components/layout/SideMenu.vue')['default']
    TemplateCard: typeof import('./src/components/template/TemplateCard.vue')['default']
    TemplateEditor: typeof import('./src/components/template/TemplateEditor.vue')['default']
    TopNav: typeof import('./src/components/layout/TopNav.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
